const app=document.getElementById("app"), statusEl=document.getElementById("status"), toastEl=document.getElementById("toast");
const cfg=window.GG_CONFIG||{}; const configured=cfg.supabaseUrl&&!cfg.supabaseUrl.startsWith("PASTE_")&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.startsWith("PASTE_");
const db=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
statusEl.textContent=configured?"Database configured":"Database setup required";
const DEFAULT_SHEET={resources:[{name:"HP",current:36,max:36},{name:"Mana",current:10,max:10},{name:"Armor",current:2,max:null}],attributes:{Strength:12,Attunement:10,Dexterity:12,Speed:12,Fortitude:12,Willpower:8,Luck:1},items:[],loot:[],weaponXp:[],skills:[],notes:""};
let active=null, saveTimer=null, hostChannel=null, hostSelected=new Map();
document.getElementById("homeBtn").onclick=()=>{cleanup();landing()};
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(s){toastEl.textContent=s;toastEl.hidden=false;setTimeout(()=>toastEl.hidden=true,2200)}
function needDb(){if(db)return true; app.innerHTML='<div class="page hero"><div class="paper landing"><h2>Database setup required</h2><p>Open <b>config.js</b> and add the Supabase project URL and publishable/anon key after running <b>supabase/schema.sql</b>.</p><button class="btn" onclick="location.reload()">Retry</button></div></div>';return false}
function cleanup(){if(hostChannel&&db)db.removeChannel(hostChannel);hostChannel=null;hostSelected.clear();active=null}
function landing(){app.innerHTML='<div class="page hero"><section class="paper landing"><h1>Gold &amp; Glory</h1><p class="subtitle">Choose how you are joining the table.</p><div class="actions"><button class="btn" id="player">Player</button><button class="btn secondary" id="host">Host</button></div></section></div>';document.getElementById("player").onclick=playerMenu;document.getElementById("host").onclick=hostLogin}
function playerMenu(){app.innerHTML='<div class="page hero"><section class="paper landing"><h2>Player</h2><div class="actions"><button class="btn" id="create">Create Character</button><button class="btn secondary" id="load">Load Character</button></div></section></div>';create.onclick=()=>playerForm(true);load.onclick=()=>playerForm(false)}
function playerForm(isCreate){if(!needDb())return;app.innerHTML='<div class="page hero"><form class="paper landing" id="pf"><h2>'+(isCreate?'Create':'Load')+' Character</h2><label class="field">Character name<input id="name" autocomplete="username" required></label><label class="field">Password<input id="pass" type="password" autocomplete="'+(isCreate?'new-password':'current-password')+'" required></label><p class="muted">Passwords may be any non-empty value.</p><div id="err" class="error"></div><button class="btn" type="submit">'+(isCreate?'Create':'Open')+'</button></form></div>';pf.onsubmit=async e=>{e.preventDefault();err.textContent="";const n=name.value.trim(),p=pass.value;if(!n||!p){err.textContent="Name and password are required.";return}const fn=isCreate?"create_character":"open_character";const {data,error}=await db.rpc(fn,{p_name:n,p_password:p});if(error||!data?.ok){err.textContent=data?.error||error?.message||"Unable to continue.";return}sessionStorage.setItem("gg_token",data.token);await openPlayer(data.character_id)}}
async function openPlayer(id){const token=sessionStorage.getItem("gg_token");const {data,error}=await db.rpc("get_character",{p_character_id:id,p_token:token});if(error||!data?.ok){toast("Could not load character");return playerMenu()}active=data.character;renderSheet()}
function mod(v){const n=Number(v)||0;return n-10}
function sign(n){return n>=0?"+"+n:String(n)}
function renderSheet(){const s=active.sheet||structuredClone(DEFAULT_SHEET);active.sheet=s;app.innerHTML='<div class="page"><div class="paper"><div class="sheet-head"><div><h1>'+esc(active.name)+'</h1><span class="save-state" id="saveState">Saved</span></div><button class="btn secondary small" id="logout">Exit Character</button></div><section><div class="resources" id="resources"></div><button class="btn secondary small" id="addResource">+ Stat</button></section><div class="grid"><section class="card"><h2>Attributes</h2><div class="stats" id="attrs"></div></section><div><section class="card section"><h2>Items</h2><div id="items"></div><button class="btn secondary small" data-add="items">+ Item</button></section><section class="card section"><h2>Loot</h2><div id="loot"></div><button class="btn secondary small" data-add="loot">+ Loot</button></section><section class="card section"><h2>Weapon Experience</h2><div id="weaponXp"></div><button class="btn secondary small" data-add="weaponXp">+ Weapon Type</button></section><section class="card section"><h2>Skills</h2><div id="skills"></div><button class="btn secondary small" data-add="skills">+ Skill</button></section><section class="card"><h2>Notes</h2><textarea id="notes" class="editable" rows="5">'+esc(s.notes)+'</textarea></section></div></div></div></div>';drawResources();drawAttrs();["items","loot","weaponXp","skills"].forEach(drawList);logout.onclick=()=>{sessionStorage.removeItem("gg_token");active=null;playerMenu()};addResource.onclick=()=>{s.resources.push({name:"New Stat",current:0,max:null});drawResources();queueSave()};document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{const k=b.dataset.add;s[k].push(k==="weaponXp"?{name:"Swords",xp:0}:k==="skills"?{name:"New Skill",value:"",notes:""}:{name:"New",value:"",notes:""});drawList(k);queueSave()});notes.oninput=e=>{s.notes=e.target.value;queueSave()}}
function drawResources(){const el=document.getElementById("resources");el.innerHTML=active.sheet.resources.map((r,i)=>'<div class="resource card"><input data-rname="'+i+'" value="'+esc(r.name)+'"><div><input type="number" data-rcur="'+i+'" value="'+Number(r.current||0)+'">'+(r.max!==null&&r.max!==undefined?' / <input type="number" data-rmax="'+i+'" value="'+Number(r.max||0)+'">':'')+'</div><button class="btn secondary small" data-rdel="'+i+'">×</button></div>').join("");el.querySelectorAll("input").forEach(x=>x.oninput=()=>{const i=Number(x.dataset.rname??x.dataset.rcur??x.dataset.rmax);if(x.dataset.rname!==undefined)active.sheet.resources[i].name=x.value;if(x.dataset.rcur!==undefined)active.sheet.resources[i].current=Number(x.value);if(x.dataset.rmax!==undefined)active.sheet.resources[i].max=Number(x.value);queueSave()});el.querySelectorAll("[data-rdel]").forEach(x=>x.onclick=()=>{active.sheet.resources.splice(Number(x.dataset.rdel),1);drawResources();queueSave()})}
function drawAttrs(){const el=document.getElementById("attrs");el.innerHTML=Object.entries(active.sheet.attributes).map(([k,v])=>'<div class="stat"><div class="mod">'+sign(mod(v))+'</div><b>'+esc(k)+'</b><input type="number" data-attr="'+esc(k)+'" value="'+Number(v)+'"></div>').join("");el.querySelectorAll("input").forEach(x=>x.oninput=()=>{active.sheet.attributes[x.dataset.attr]=Number(x.value);drawAttrs();queueSave()})}
function drawList(k){const el=document.getElementById(k);const arr=active.sheet[k]||[];el.innerHTML=arr.map((x,i)=>{if(k==="weaponXp")return '<div class="row xp"><input data-f="name" data-i="'+i+'" value="'+esc(x.name)+'" placeholder="Weapon type"><input type="number" data-f="xp" data-i="'+i+'" value="'+Number(x.xp||0)+'" placeholder="XP"><button class="btn danger small" data-del="'+i+'">×</button></div>';return '<div class="row '+(k==="skills"?"skill":"")+'"><input data-f="name" data-i="'+i+'" value="'+esc(x.name)+'" placeholder="Name"><input data-f="value" data-i="'+i+'" value="'+esc(x.value)+'" placeholder="Value"><input data-f="notes" data-i="'+i+'" value="'+esc(x.notes)+'" placeholder="Notes"><button class="btn danger small" data-del="'+i+'">×</button></div>'}).join("");el.querySelectorAll("input").forEach(x=>x.oninput=()=>{arr[Number(x.dataset.i)][x.dataset.f]=x.dataset.f==="xp"?Number(x.value):x.value;queueSave()});el.querySelectorAll("[data-del]").forEach(x=>x.onclick=()=>{arr.splice(Number(x.dataset.del),1);drawList(k);queueSave()})}
function queueSave(){saveState.textContent="Unsaved changes…";clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,700)}
async function saveNow(){if(!active)return;saveState.textContent="Saving…";const {data,error}=await db.rpc("save_character",{p_character_id:active.id,p_token:sessionStorage.getItem("gg_token"),p_sheet:active.sheet});saveState.textContent=(!error&&data?.ok)?"Saved":"Save failed";if(!error&&data?.ok)active.updated_at=data.updated_at}
function hostLogin(){if(!needDb())return;app.innerHTML='<div class="page hero"><form class="paper landing" id="hf"><h2>Host</h2><label class="field">Host password<input id="hp" type="password" required></label><div id="herr" class="error"></div><button class="btn">Open Host Screen</button><p class="muted">Set the host password when you run the database setup.</p></form></div>';hf.onsubmit=async e=>{e.preventDefault();const {data,error}=await db.rpc("host_login",{p_password:hp.value});if(error||!data?.ok){herr.textContent=data?.error||"Incorrect host password.";return}sessionStorage.setItem("gg_host_token",data.token);renderHost()}}
async function renderHost(){const token=sessionStorage.getItem("gg_host_token");const {data,error}=await db.rpc("host_list_characters",{p_token:token});if(error||!data?.ok){toast("Host session expired");return hostLogin()}app.innerHTML='<div class="page host-layout"><aside class="paper browser"><div class="sheet-head"><h2>Characters</h2><button class="btn secondary small" id="hostExit">Exit</button></div><div id="charList"></div></aside><section><div class="host-grid" id="hostGrid"><div class="paper"><h2>Host Dashboard</h2><p>Select characters from the list. Their cards update automatically when players save changes.</p></div></div></section></div>';hostExit.onclick=()=>{sessionStorage.removeItem("gg_host_token");cleanup();landing()};drawCharList(data.characters);hostChannel=db.channel("gg-host").on("postgres_changes",{event:"UPDATE",schema:"public",table:"characters"},payload=>hostRefreshOne(payload.new.id)).subscribe()}
function drawCharList(chars){charList.innerHTML=chars.map(c=>'<button class="char-pick" data-id="'+c.id+'"><b>'+esc(c.name)+'</b><br><span class="muted">'+new Date(c.updated_at).toLocaleString()+'</span></button>').join("");charList.querySelectorAll("button").forEach(b=>b.onclick=()=>hostAdd(b.dataset.id))}
async function hostAdd(id){const {data,error}=await db.rpc("host_get_character",{p_token:sessionStorage.getItem("gg_host_token"),p_character_id:id});if(error||!data?.ok)return toast("Could not load character");hostSelected.set(id,data.character);drawHostGrid()}
async function hostRefreshOne(id){if(!hostSelected.has(id))return;const {data}=await db.rpc("host_get_character",{p_token:sessionStorage.getItem("gg_host_token"),p_character_id:id});if(data?.ok){hostSelected.set(id,data.character);drawHostGrid()}const list=await db.rpc("host_list_characters",{p_token:sessionStorage.getItem("gg_host_token")});if(list.data?.ok)drawCharList(list.data.characters)}
function drawHostGrid(){if(!hostSelected.size){hostGrid.innerHTML='<div class="paper"><h2>Host Dashboard</h2><p>Select a character.</p></div>';return}hostGrid.innerHTML=[...hostSelected.values()].map(c=>{const s=c.sheet||DEFAULT_SHEET;const res=(s.resources||[]).slice(0,6).map(r=>'<div><b>'+esc(r.name)+'</b><br>'+esc(r.current)+(r.max!=null?' / '+esc(r.max):'')+'</div>').join("");const at=Object.entries(s.attributes||{}).map(([k,v])=>'<div><b>'+esc(k)+'</b> '+v+' ('+sign(mod(v))+')</div>').join("");return '<article class="paper mini-sheet" data-card="'+c.id+'"><button class="btn secondary small close" data-close="'+c.id+'">×</button><h2>'+esc(c.name)+'</h2><div class="mini-stats">'+res+'</div><div class="mini-attrs">'+at+'</div><p class="muted">Updated '+new Date(c.updated_at).toLocaleString()+'</p></article>'}).join("");hostGrid.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{hostSelected.delete(b.dataset.close);drawHostGrid()})}
landing();
